<a href="https://colab.research.google.com/github/vladmsnk/Partial-Diff-equations-hm/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [190]:
import pandas as pd
from sklearn import preprocessing

In [191]:
df = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
df.head()

,id,Leave_Next_Month,Gender,Pensioner,Married,Children,Months_with_company,Phone_Service,Multiple_Lines,Internet_Service,...,Online_Backup,Device_Protection,Tech_Support,Streaming_TV,Streaming_Movies,Type_contract,Paperless_Billing,Payment_Method,Monthly_Payment,Total_Payment
0,4,1,F,0,N,N,2,Y,N,Fiber optic,...,N,N,N,N,N,Per_month,Y,Check_electron,70.70,151.65
1,7,0,F,0,N,N,10,N,No_phone,DSL,...,N,N,N,N,N,Per_month,N,Check_mailed,29.75,301.9
2,8,1,F,0,Y,N,28,Y,Y,Fiber optic,...,N,Y,Y,Y,Y,Per_month,Y,Check_electron,104.80,3046.05
3,9,0,M,0,N,Y,62,Y,N,DSL,...,Y,N,N,N,N,Year-1,N,Bank_transfer_auto,56.15,3487.95
4,11,0,M,0,N,N,16,Y,N,N,...,No_internet,No_internet,No_internet,No_internet,No_internet,Year-2,N,Credit_card_auto,18.95,326.8

In [192]:
df.dtypes

id                       int64
Leave_Next_Month         int64
Gender                  object
Pensioner                int64
Married                 object
Children                object
Months_with_company      int64
Phone_Service           object
Multiple_Lines          object
Internet_Service        object
Online_Security         object
Online_Backup           object
Device_Protection       object
Tech_Support            object
Streaming_TV            object
Streaming_Movies        object
Type_contract           object
Paperless_Billing       object
Payment_Method          object
Monthly_Payment        float64
Total_Payment           object
dtype: object

In [193]:
df.isnull().sum()

id                     0
Leave_Next_Month       0
Gender                 0
Pensioner              0
Married                0
Children               0
Months_with_company    0
Phone_Service          0
Multiple_Lines         0
Internet_Service       0
Online_Security        0
Online_Backup          0
Device_Protection      0
Tech_Support           0
Streaming_TV           0
Streaming_Movies       0
Type_contract          0
Paperless_Billing      0
Payment_Method         0
Monthly_Payment        0
Total_Payment          0
dtype: int64

In [194]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3521 entries, 0 to 3520
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   3521 non-null   int64
 1   Leave_Next_Month     3521 non-null   int64
 2   Gender               3521 non-null   object
 3   Pensioner            3521 non-null   int64
 4   Married              3521 non-null   object
 5   Children             3521 non-null   object
 6   Months_with_company  3521 non-null   int64
 7   Phone_Service        3521 non-null   object
 8   Multiple_Lines       3521 non-null   object
 9   Internet_Service     3521 non-null   object
 10  Online_Security      3521 non-null   object
 11  Online_Backup        3521 non-null   object
 12  Device_Protection    3521 non-null   object
 13  Tech_Support         3521 non-null   object
 14  Streaming_TV         3521 non-null   object
 15  Streaming_Movies     3521 non-null   object
 16  Type_contract        3521 non-null   object
 17  Paperless_Billing    3521 non-null   object
 18  Payment_Method       3521 non-null   object
 19  Monthly_Payment      3521 non-null   float64
 20  Total_Payment        3521 non-null   object
dtypes: float64(1), int64(4), object(16)
memory usage: 577.8+ KB

In [195]:
categorical_columns = df.select_dtypes(include='object').columns

In [196]:
label_encode_columns = []
one_hot_encode_columns = []

for column in df.columns:
    unique_values = df[column].nunique()
    if unique_values == 2:
        label_encode_columns.append(column)
    elif unique_values > 2 and unique_values < 5:
        one_hot_encode_columns.append(column)

In [197]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
for column in label_encode_columns:
    df[column] = label_encoder.fit_transform(df[column])

In [198]:
df.head()

,id,Leave_Next_Month,Gender,Pensioner,Married,Children,Months_with_company,Phone_Service,Multiple_Lines,Internet_Service,...,Online_Backup,Device_Protection,Tech_Support,Streaming_TV,Streaming_Movies,Type_contract,Paperless_Billing,Payment_Method,Monthly_Payment,Total_Payment
0,4,1,0,0,0,0,2,1,N,Fiber optic,...,N,N,N,N,N,Per_month,1,Check_electron,70.70,151.65
1,7,0,0,0,0,0,10,0,No_phone,DSL,...,N,N,N,N,N,Per_month,0,Check_mailed,29.75,301.9
2,8,1,0,0,1,0,28,1,Y,Fiber optic,...,N,Y,Y,Y,Y,Per_month,1,Check_electron,104.80,3046.05
3,9,0,1,0,0,1,62,1,N,DSL,...,Y,N,N,N,N,Year-1,0,Bank_transfer_auto,56.15,3487.95
4,11,0,1,0,0,0,16,1,N,N,...,No_internet,No_internet,No_internet,No_internet,No_internet,Year-2,0,Credit_card_auto,18.95,326.8

In [199]:
one_hot_encode_columns

['Multiple_Lines',
 'Internet_Service',
 'Online_Security',
 'Online_Backup',
 'Device_Protection',
 'Tech_Support',
 'Streaming_TV',
 'Streaming_Movies',
 'Type_contract',
 'Payment_Method']

In [200]:
df = pd.get_dummies(data=df, columns=one_hot_encode_columns)

In [201]:
import xgboost as xgb

In [202]:
object_columns = df.select_dtypes(include='object').columns
df['Total_Payment'] = df['Total_Payment'].replace(r'^\s*$', float('nan'), regex=True)
df['Total_Payment'] = pd.to_numeric(df['Total_Payment'], errors='coerce')

In [203]:
X = df.drop('Leave_Next_Month',  axis=1)
y = df['Leave_Next_Month']

In [204]:
dtrain = xgb.DMatrix(data=X, label=y)

In [205]:
params = {"objective":"binary:logistic",'colsample_bytree': 0.4,'learning_rate': 0.1,
                'max_depth': 5, 'alpha': 10}
res = xgb.cv(
    params,
    dtrain,
    num_boost_round=10,
    nfold=5,
    metrics="auc",
    seed=0,
    callbacks=[
        xgb.callback.EvaluationMonitor(show_stdv=False),
        xgb.callback.EarlyStopping(3),
    ],
)
best_num_boost_rounds = res.shape[0]

[0]	train-auc:0.80004	test-auc:0.78928
[1]	train-auc:0.82515	test-auc:0.81689
[2]	train-auc:0.83568	test-auc:0.82683
[3]	train-auc:0.84179	test-auc:0.82992
[4]	train-auc:0.84742	test-auc:0.83534
[5]	train-auc:0.85266	test-auc:0.83960
[6]	train-auc:0.85279	test-auc:0.84098
[7]	train-auc:0.85482	test-auc:0.84176
[8]	train-auc:0.85550	test-auc:0.84353
[9]	train-auc:0.85633	test-auc:0.84340

In [206]:
categorical_columns = df_test.select_dtypes(include='object').columns
label_encode_columns = []
one_hot_encode_columns = []

for column in df_test.columns:
    unique_values = df_test[column].nunique()
    if unique_values == 2:
        label_encode_columns.append(column)
    elif unique_values > 2 and unique_values < 5:
        one_hot_encode_columns.append(column)
label_encoder = LabelEncoder()
for column in label_encode_columns:
    df_test[column] = label_encoder.fit_transform(df_test[column])
df_test = pd.get_dummies(data=df_test, columns=one_hot_encode_columns)
df_test['Total_Payment'] = df_test['Total_Payment'].replace(r'^\s*$', float('nan'), regex=True)
df_test['Total_Payment'] = pd.to_numeric(df_test['Total_Payment'], errors='coerce')

In [208]:

best_num_boost_rounds = res.shape[0]
X_test = df_test
dtest = xgb.DMatrix(X_test)

model = xgb.train(params, dtrain, num_boost_round=best_num_boost_rounds)

y_pred = model.predict(dtest)

In [217]:
result = pd.DataFrame({'id': df_test['id'], 'Leave_Next_Month': y_pred})
result.to_csv('predictions.csv', index=False)